# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'C:/College/Thesis/VivadoProjects/SHA1_BRAM/tb_behav.wcfg'.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.cache/wt [current_project]
set_property parent.project_path C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo c:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/Init.coe
add_files -quiet c:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/new/uart_tx.v
  C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/new/counter.v
  C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/new/core_logic.v
  C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/new/HashIn.v
  C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files C:/College/Thesis/VivadoProjects/SHA1_BRAM_12/SHA1_BRAM.srcs/constrs_1/new/constr.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
